---
  - name: making sure octavia worker configuration directory exists
    file:
      path: "{{ octavia_confd_prefix }}{{ ca_private_key_path | dirname }}"
      state: directory
      selevel: s0
      setype: svirt_sandbox_file_t
    become: true
  - name: Copying key info to octavia
    become: true
    copy:
      content: "{{ item.content }}"
      dest: "{{ octavia_confd_prefix }}/{{ item.path }}"
      selevel: s0
      setype: svirt_sandbox_file_t
    no_log: true
    loop:
        - { content: "{{ private_key_content }}", path: "{{ ca_private_key_path }}" }
        - { content: "{{ ca_cert_content }}", path: "{{ ca_cert_path }}" }
        - { content: "{{ service_pem_content }}" , path: "{{ client_cert_path }}" }
    notify:
      - octavia config updated
