---
  - name: setting [controller_worker]/amp_boot_network_list
    become: true
    become_user: root
    ini_file:
      path: "{{ octavia_confd_prefix }}/etc/octavia/post-deploy.conf"
      section: controller_worker
      option: amp_boot_network_list
      value: "{{ lb_mgmt_net_id }}"
      selevel: s0
      setype: svirt_sandbox_file_t
  - name: setting [controller_worker]/amp_secgroup_list
    become: true
    become_user: root
    ini_file:
      path: "{{ octavia_confd_prefix }}/etc/octavia/post-deploy.conf"
      section: controller_worker
      option: amp_secgroup_list
      value: "{{ lb_mgmt_secgroup_id }}"
      selevel: s0
      setype: svirt_sandbox_file_t
  - name: setting [health_manager]/bind_ip
    become: true
    become_user: root
    ini_file:
      path: "{{ octavia_confd_prefix }}/etc/octavia/post-deploy.conf"
      section: health_manager
      option: bind_ip
      value: "{{ mgmt_port_ip }}"
      selevel: s0
      setype: svirt_sandbox_file_t
  - name: gather facts about the service project
    shell: |
      openstack project show "{{ auth_project_name }}" -c id -f value
    register: project_id_result
  - name: setting [controller_worker]/amp_image_owner_id
    become: true
    become_user: root
    ini_file:
      path: "{{ octavia_confd_prefix }}/etc/octavia/post-deploy.conf"
      section: controller_worker
      option: amp_image_owner_id
      value: "{{ project_id_result.stdout }}"
